var EnglishLetters = /** @class */ (function () {
    function EnglishLetters() {
    }
    EnglishLetters.prototype.playWord = function () {
        return this.name + " " + this.word;
    };
    return EnglishLetters;
}());
;
var EnglishLetterA = new EnglishLetters();
EnglishLetterA.name = "A";
EnglishLetterA.word = "Apple";
EnglishLetterA.simpleImg = "./Img/Apple.jpeg";
console.log(EnglishLetterA.playWord());
var EnglishLetterB = new EnglishLetters();
EnglishLetterB.name = "B";
EnglishLetterB.word = "Ball";
EnglishLetterB.simpleImg = "./Img/Apple.jpeg";
console.log(EnglishLetterB.playWord());
var EnglishLetterC = new EnglishLetters();
EnglishLetterC.name = "C";
EnglishLetterC.word = "Car";
EnglishLetterC.simpleImg = "./Img/Apple.jpeg";
console.log(EnglishLetterC.playWord());
var EnglishLetterD = new EnglishLetters();
EnglishLetterD.name = "D";
EnglishLetterD.word = "Dog";
EnglishLetterD.simpleImg = "./Img/Apple.jpeg";
console.log(EnglishLetterD.playWord());
var EnglishLetterE = new EnglishLetters();
EnglishLetterE.name = "E";
EnglishLetterE.word = "Elephant";
EnglishLetterE.simpleImg = "./Img/Apple.jpeg";
console.log(EnglishLetterE.playWord());
var EnglishLetterF = new EnglishLetters();
EnglishLetterF.name = "F";
EnglishLetterF.word = "Fish";
console.log(EnglishLetterF.playWord());
var EnglishLetterG = new EnglishLetters();
EnglishLetterG.name = "G";
EnglishLetterG.word = "Goat";
console.log(EnglishLetterG.playWord());
var EnglishLetterH = new EnglishLetters();
EnglishLetterH.name = "H";
EnglishLetterH.word = "Hourse";
console.log(EnglishLetterH.playWord());
var EnglishLetterI = new EnglishLetters();
EnglishLetterI.name = "I";
EnglishLetterI.word = "Icecream";
console.log(EnglishLetterI.playWord());
var EnglishLetterJ = new EnglishLetters();
EnglishLetterJ.name = "J";
EnglishLetterJ.word = "Jacket";
console.log(EnglishLetterJ.playWord());
var EnglishLetterK = new EnglishLetters();
EnglishLetterK.name = "K";
EnglishLetterK.word = "Key";
console.log(EnglishLetterK.playWord());
var EnglishLetterL = new EnglishLetters();
EnglishLetterL.name = "L";
EnglishLetterL.word = "Lion";
console.log(EnglishLetterL.playWord());
var EnglishLetterM = new EnglishLetters();
EnglishLetterM.name = "M";
EnglishLetterM.word = "Monckey";
console.log(EnglishLetterM.playWord());
var EnglishLetterN = new EnglishLetters();
EnglishLetterN.name = "N";
EnglishLetterN.word = "Newspaper";
console.log(EnglishLetterN.playWord());
var EnglishLetterO = new EnglishLetters();
EnglishLetterO.name = "O";
EnglishLetterO.word = "Orange";
console.log(EnglishLetterO.playWord());
var EnglishLetterP = new EnglishLetters();
EnglishLetterP.name = "P";
EnglishLetterP.word = "Pen";
console.log(EnglishLetterP.playWord());
var EnglishLetterQ = new EnglishLetters();
EnglishLetterQ.name = "Q";
EnglishLetterQ.word = "Queen";
console.log(EnglishLetterQ.playWord());
var EnglishLetterR = new EnglishLetters();
EnglishLetterR.name = "R";
EnglishLetterR.word = "Ring";
console.log(EnglishLetterR.playWord());
var EnglishLetterS = new EnglishLetters();
EnglishLetterS.name = "S";
EnglishLetterS.word = "Snak";
console.log(EnglishLetterS.playWord());
var EnglishLetterT = new EnglishLetters();
EnglishLetterT.name = "T";
EnglishLetterT.word = "Train";
console.log(EnglishLetterT.playWord());
var EnglishLetterU = new EnglishLetters();
EnglishLetterU.name = "U";
EnglishLetterU.word = "Umbrella";
console.log(EnglishLetterU.playWord());
var EnglishLetterV = new EnglishLetters();
EnglishLetterV.name = "V";
EnglishLetterV.word = "Violin";
console.log(EnglishLetterV.playWord());
var EnglishLetterW = new EnglishLetters();
EnglishLetterW.name = "W";
EnglishLetterW.word = "Water";
console.log(EnglishLetterW.playWord());
var EnglishLetterX = new EnglishLetters();
EnglishLetterX.name = "X";
EnglishLetterX.word = "Xylophone";
console.log(EnglishLetterX.playWord());
var EnglishLetterY = new EnglishLetters();
EnglishLetterY.name = "Y";
EnglishLetterY.word = "Yellow";
console.log(EnglishLetterY.playWord());
var EnglishLetterZ = new EnglishLetters();
EnglishLetterZ.name = "Z";
EnglishLetterZ.word = "Zero";
console.log(EnglishLetterZ.playWord());
var myPword = document.getElementsByClassName('word');
var myEnglishLetters = [EnglishLetterA, EnglishLetterB, EnglishLetterC, EnglishLetterD, EnglishLetterE, EnglishLetterF, EnglishLetterG, EnglishLetterH, EnglishLetterI, EnglishLetterJ, EnglishLetterK, EnglishLetterL, EnglishLetterM, EnglishLetterN, EnglishLetterO, EnglishLetterP, EnglishLetterQ, EnglishLetterR, EnglishLetterS, EnglishLetterT, EnglishLetterU, EnglishLetterV, EnglishLetterW, EnglishLetterX, EnglishLetterY, EnglishLetterZ];
var i;
var _loop_1 = function () {
    var myP = document.createElement('p');
    var myDivLetter = document.createElement('div').appendChild(myP);
    var myExample = document.getElementById('word');
    var mySimpleWord = myEnglishLetters[i].word;
    var mySimpleImg = myEnglishLetters[i].simpleImg;
    var myExImg = document.getElementById('Simg');
    myP.classList.add("leb");
    myP.innerText = myEnglishLetters[i].name;
    myDivLetter.addEventListener('click', function () {
        myExample.innerHTML = mySimpleWord;
        myExImg.setAttribute("src", (mySimpleImg));
    });
    document.getElementById('buttons').appendChild(myDivLetter).classList.add("clicks");
};
for (i = 0; i <= 25; i++) {
    _loop_1();
}
;
var myDivArray = [document.getElementsByClassName('clicks')];
